language: rust
os:
  - linux
  - windows
  - osx
rust:
  - beta
  - nightly
cache: cargo
branches:
  only:
    - master
script:
  - cargo build
  - cargo test
env:
  - RUST_BACKTRACE=1