[package]
name = "async-injector"
version = "0.6.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/async-injector"
homepage = "https://github.com/udoprog/async-injector"
documentation = "https://docs.rs/async-injector"
description = """
Reactive dependency injection for Rust.
"""

[dependencies]
hashbrown = "0.7.1"
smallvec = "1.4.0"
log = "0.4.8"
async-injector-derive = { version = "0.4.0", path = "./async-injector-derive" }
async-trait = "0.1.30"
serde-hashkey = "0.2.2"
serde = { version = "1.0.106", features = ["derive"] }
futures-util = "0.3.4"
lazy_static = { version = "1.4.0", optional = true }
tokio = { version = "0.2.19", features = ["sync"] }

[dev-dependencies]
futures = "0.3.4"
anyhow = "1.0.28"
tokio = { version = "0.2.19", features = ["full"] }

[features]
static = ["lazy_static"]