[package]
name = "async-injector"
version = "0.15.3"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/async-injector"
homepage = "https://github.com/udoprog/async-injector"
documentation = "https://docs.rs/async-injector"
description = """
Reactive dependency injection for Rust.
"""

[dependencies]
async-injector-derive = { version = "0.15.3", path = "./async-injector-derive" }

async-stream = "0.3.0"
hashbrown = "0.9.1"
serde = { version = "1.0.117", features = ["derive"] }
serde-hashkey = "0.3.0"
tokio = { version = "1.0.0", features = ["sync", "macros"] }
tokio-stream = "0.1.0"

[dev-dependencies]
anyhow = "1.0.38"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread"] }
