[package]
name = "async-injector"
version = "0.18.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/async-injector"
homepage = "https://github.com/udoprog/async-injector"
documentation = "https://docs.rs/async-injector"
description = """
Reactive dependency injection for Rust.
"""

[dependencies]
async-injector-derive = { version = "0.18.0", path = "./async-injector-derive" }

hashbrown = "0.11.2"
serde = { version = "1.0.130", features = ["derive"] }
serde-hashkey = "0.4.0"
tokio = { version = "1.10.1", features = ["sync", "macros"] }

[dev-dependencies]
anyhow = "1.0.43"
tokio = { version = "1.10.1", features = ["rt", "rt-multi-thread", "time"] }

[workspace]
members = [
    "async-injector-derive"
]
