[package]
name = "async-injector"
version = "0.2.2"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/async-injector"
homepage = "https://github.com/udoprog/async-injector"
documentation = "https://docs.rs/async-injector"
description = """
Reactive dependency injection for Rust.
"""

[dependencies]
parking_lot = "0.9.0"
hashbrown = "0.5.0"
smallvec = "0.6.10"
log = "0.4.8"
async-injector-derive = { version = "0.2.0", path = "./async-injector-derive" }
async-trait = "0.1.7"
serde-hashkey = "0.2.0"
serde = { version = "1.0.99", features = ["derive"] }
futures-util-preview = "=0.3.0-alpha.19"
futures-channel-preview = "=0.3.0-alpha.19"

[dev-dependencies]
failure = "0.1.5"

[dev-dependencies.futures]
package = "futures-preview"
version = "=0.3.0-alpha.19"
features = ["async-await"]