[package]
name = "async-injector"
version = "0.13.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/async-injector"
homepage = "https://github.com/udoprog/async-injector"
documentation = "https://docs.rs/async-injector"
description = """
Reactive dependency injection for Rust.
"""

[dependencies]
hashbrown = "0.9.1"
smallvec = "1.4.2"
log = "0.4.11"
async-injector-derive = { version = "0.11.1", path = "./async-injector-derive" }
serde-hashkey = "0.3.0"
serde = { version = "1.0.117", features = ["derive"] }
futures-util = "0.3.8"
lazy_static = { version = "1.4.0", optional = true }
tokio = { version = "1.0.0", features = ["sync", "macros"] }
tokio-stream = "0.1.0"
async-stream = "0.3.0"

[dev-dependencies]
futures = "0.3.8"
anyhow = "1.0.33"
tokio = { version = "1.0.0", features = ["full"] }

[features]
static = ["lazy_static"]
