[package]
name = "async-injector"
version = "0.10.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/async-injector"
homepage = "https://github.com/udoprog/async-injector"
documentation = "https://docs.rs/async-injector"
description = """
Reactive dependency injection for Rust.
"""

[dependencies]
hashbrown = "0.9.1"
smallvec = "1.4.2"
log = "0.4.11"
async-injector-derive = { version = "0.10.0", path = "./async-injector-derive" }
async-trait = "0.1.41"
serde-hashkey = "0.2.2"
serde = { version = "1.0.117", features = ["derive"] }
futures-util = "0.3.7"
lazy_static = { version = "1.4.0", optional = true }
tokio = { version = "0.3.1", features = ["sync", "stream", "macros"] }

[dev-dependencies]
futures = "0.3.7"
anyhow = "1.0.33"
tokio = { version = "0.3.1", features = ["full"] }

[features]
static = ["lazy_static"]
