[package]
name = "async-injector-derive"
version = "0.16.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/async-injector"
homepage = "https://github.com/udoprog/async-injector"
documentation = "https://docs.rs/async-injector"
description = """
A derive to help construct dependent values in async-injector.
"""

[dependencies]
darling = "0.12.0"
proc-macro2 = "1.0.24"
quote = "1.0.8"
syn = { version = "1.0.59", features = ["full", "visit-mut"] }

[dev-dependencies]
async-injector = { version = "0.16.0", path = ".." }

serde = { version = "1.0.121", features = ["derive"] }
tokio = { version = "1.1.0", features = ["rt", "rt-multi-thread", "sync", "macros"] }
tokio-stream = "0.1.2"

[lib]
proc-macro = true
