[package]
name = "async-injector-derive"
version = "0.14.1"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/async-injector"
homepage = "https://github.com/udoprog/async-injector"
documentation = "https://docs.rs/async-injector"
description = """
A derive to help construct dependent values in async-injector.
"""

[dependencies]
darling = "0.10.2"
proc-macro2 = "1.0.10"
quote = "1.0.3"
syn = { version = "1.0.18", features = ["full", "visit-mut"] }

[dev-dependencies]
async-injector = { version = "0.14.1", path = ".." }

serde = { version = "1.0.106", features = ["derive"] }
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "sync", "macros"] }
tokio-stream = "0.1.0"

[lib]
proc-macro = true
