[package]
name = "async-injector-derive"
version = "0.2.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/async-injector"
homepage = "https://github.com/udoprog/async-injector"
documentation = "https://docs.rs/async-injector"
description = """
A derive to help construct dependent values in async-injector.
"""

[dependencies]
syn = { version = "0.15.42", features = ["full", "visit-mut"] }
quote = "0.6.13"
proc-macro2 = "0.4.30"
darling = "0.9.0"

[lib]
proc-macro = true