[package]
name = "async-injector-derive"
version = "0.4.1"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/async-injector"
homepage = "https://github.com/udoprog/async-injector"
documentation = "https://docs.rs/async-injector"
description = """
A derive to help construct dependent values in async-injector.
"""

[dependencies]
syn = { version = "1.0.18", features = ["full", "visit-mut"] }
quote = "1.0.3"
proc-macro2 = "1.0.10"
darling = "0.10.2"

[lib]
proc-macro = true