[package]
name = "async-injector-derive"
version = "0.18.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/async-injector"
homepage = "https://github.com/udoprog/async-injector"
documentation = "https://docs.rs/async-injector"
description = """
A derive to help construct dependent values in async-injector.
"""

[dependencies]
darling = "0.13.0"
proc-macro2 = "1.0.28"
quote = "1.0.9"
syn = { version = "1.0.75", features = ["full", "visit-mut"] }

[dev-dependencies]
async-injector = { version = "0.18.0", path = ".." }

serde = { version = "1.0.130", features = ["derive"] }
tokio = { version = "1.10.1", features = ["rt", "rt-multi-thread", "sync", "macros"] }
tokio-stream = "0.1.7"

[lib]
proc-macro = true
